"""Reviewed bilingual mechanism facts for the thirty MiniLucene Stages."""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class LessonFacts:
    title_en: str
    title_zh: str
    problem_en: str
    problem_zh: str
    failure_en: str
    failure_zh: str
    concepts_en: str
    concepts_zh: str
    runtime_en: str
    runtime_zh: str
    statement_en: str
    statement_zh: str


FACTS = (
    LessonFacts(
        "Field and document contract",
        "字段与文档契约",
        "An index cannot interpret arbitrary dictionaries without fixing field type, storage, indexing, and analyzer rules.",
        "索引若不固定字段类型、存储、索引与 Analyzer 规则，就无法解释任意字典。",
        "The contracts submit unknown fields, duplicate names, missing required values, and values of the wrong Python type.",
        "契约提交未知字段、重名字段、缺失必填值与错误 Python 类型。",
        "A schema is the closed interpretation contract; a Document is validated input, not yet an indexed representation.",
        "Schema 是封闭的解释契约；Document 是校验后的输入，还不是索引表示。",
        "Validation resolves every field definition before analysis or storage and returns typed failures before state changes.",
        "Validation 在 Analysis 或 Storage 前解析每个 Field Definition，并在状态变化前返回类型化失败。",
        "Rejecting unknown and ill-typed values at the boundary prevents later codecs and scorers from guessing semantics.",
        "在边界拒绝未知与错类型值，防止后续 Codec 与 Scorer 猜测语义。",
    ),
    LessonFacts(
        "Positional analysis",
        "位置化文本分析",
        "Raw text cannot support term, phrase, or highlighting semantics until token attributes are stable.",
        "原始文本只有形成稳定 Token 属性后，才能支持 Term、Phrase 与 Highlight 语义。",
        "The suite uses punctuation, stop words, position gaps, offsets, and invalid token ranges to expose lossy analyzers.",
        "测试用标点、Stop Word、Position Gap、Offset 与非法 Token Range 暴露有损 Analyzer。",
        "A Token carries term text, position, and source offsets; an Analyzer is a deterministic pipeline over those attributes.",
        "Token 携带 Term、Position 与源 Offset；Analyzer 是这些属性上的确定性 Pipeline。",
        "Character filtering and tokenization create evidence; filters normalize or remove tokens while preserving position and offset meaning.",
        "字符过滤与 Tokenization 产生证据；Filter 在保留 Position 与 Offset 含义的前提下归一化或移除 Token。",
        "Position increments preserve phrase distance across removed tokens, while offsets preserve the original text span for highlighting.",
        "Position Increment 保留被移除 Token 造成的 Phrase 距离，Offset 保留 Highlight 所需的原文范围。",
    ),
    LessonFacts(
        "Immutable RAM inverted index",
        "不可变 RAM 倒排索引",
        "Validated documents still require a structure that answers which documents contain a term and where it occurs.",
        "校验后的 Document 仍需要一种结构回答某 Term 出现在哪些 Document、哪些位置。",
        "Tests index repeated terms and multiple fields, then mutate source inputs to prove the built segment does not change.",
        "测试索引重复 Term 与多 Field，再修改源输入以证明已构建 Segment 不会变化。",
        "A posting binds term, doc ID, frequency, and positions; norms store per-field length; an immutable segment freezes one indexing generation.",
        "Posting 绑定 Term、Doc ID、Frequency 与 Position；Norm 保存 Field Length；不可变 Segment 冻结一次索引代次。",
        "The builder analyzes indexed fields, assigns local doc IDs, accumulates ordered postings and norms, then publishes immutable mappings.",
        "Builder 分析可索引字段、分配 Local Doc ID、累积有序 Posting 与 Norm，最后发布不可变 Mapping。",
        "Sorting terms, documents, and positions makes the segment deterministic and safe to share without mutation locks.",
        "对 Term、Document 与 Position 排序，使 Segment 确定且可无锁共享。",
    ),
    LessonFacts(
        "Closed query matching",
        "封闭 Query 匹配",
        "An index has postings but no explicit language for composing term, phrase, and boolean predicates.",
        "索引已有 Posting，却没有显式语言组合 Term、Phrase 与 Boolean Predicate。",
        "The tests build nested AND, OR, NOT, and phrase queries whose positional or set behavior differs under naive evaluation.",
        "测试构造嵌套 AND、OR、NOT 与 Phrase Query，使朴素求值暴露 Position 或集合语义错误。",
        "A closed AST enumerates supported query forms; matching is a pure operation over a reader snapshot and returns document evidence.",
        "封闭 AST 枚举支持的 Query 形式；Matching 是 Reader Snapshot 上的纯操作并返回 Document Evidence。",
        "Leaf queries read postings, phrase matching aligns positions, and boolean nodes combine child results under explicit occurrence rules.",
        "Leaf Query 读取 Posting，Phrase Matching 对齐 Position，Boolean Node 按显式 Occur Rule 组合子结果。",
        "Keeping the AST closed makes unsupported syntax impossible to smuggle into runtime matching as an unvalidated string.",
        "保持 AST 封闭，避免不受支持的语法以未校验字符串混入运行时 Matching。",
    ),
    LessonFacts(
        "Snapshot corpus statistics",
        "快照级语料统计",
        "Scoring each segment with local statistics makes identical terms incomparable across a multi-segment index.",
        "用 Segment 局部统计评分，会让多 Segment 索引中的相同 Term 不可比较。",
        "The counterexample distributes documents unevenly across segments and checks document frequency and average field length over the whole snapshot.",
        "反例把 Document 不均匀分布在多个 Segment，并检查整个 Snapshot 上的 DF 与平均 Field Length。",
        "Corpus statistics belong to a reader snapshot: live document count, per-field length totals, and term document frequency.",
        "Corpus Statistic 属于 Reader Snapshot：Live Document Count、各 Field Length Total 与 Term DF。",
        "Opening a search reader walks all visible segment views once and freezes aggregate statistics beside them.",
        "打开 Search Reader 时遍历全部可见 Segment View，并把聚合统计与它们一起冻结。",
        "Freezing statistics with the same segment set used for matching prevents scores from mixing two visibility generations.",
        "统计与 Matching 使用的 Segment Set 一起冻结，避免 Score 混合两个可见性代次。",
    ),
    LessonFacts(
        "Global BM25 ranking",
        "全局 BM25 排名",
        "Matching says which documents qualify but not how limited result slots should be ordered.",
        "Matching 只说明哪些 Document 合格，却不说明有限结果槽位如何排序。",
        "Tests vary term frequency, document length, zero average length, and field boosts to expose unstable or divided-by-zero scoring.",
        "测试改变 TF、Document Length、零平均长度与 Field Boost，暴露不稳定或除零评分。",
        "BM25 combines global IDF with saturating term frequency and length normalization; boosts express explicit field/query weight.",
        "BM25 把全局 IDF、饱和 TF 与 Length Normalization 组合起来；Boost 表达显式字段或 Query 权重。",
        "The scorer visits matching terms, reads snapshot statistics and per-document norms, accumulates child scores, then applies deterministic tie-breaking.",
        "Scorer 遍历匹配 Term，读取 Snapshot Statistic 与 Document Norm，累积子分数，再应用确定性 Tie Break。",
        "The zero-average guard preserves a finite normalization baseline instead of letting an empty field poison every score.",
        "零平均值保护建立有限归一化基线，避免空 Field 污染所有 Score。",
    ),
    LessonFacts(
        "Bounded Top-K retrieval",
        "有界 Top-K 检索",
        "Sorting every matching document wastes memory when a caller requests only a small number of hits.",
        "调用方只要少量 Hit 时，对全部匹配 Document 排序会浪费内存。",
        "The tests create more matches than K, score ties, and stored fields large enough to expose eager fetching.",
        "测试制造多于 K 的 Match、Score Tie 与足够大的 Stored Field，暴露提前 Fetch。",
        "A bounded collector retains only competitive score/doc pairs; search separates collect from fetching stored winners.",
        "有界 Collector 只保留有竞争力的 Score/Doc Pair；Search 把 Collect 与 Fetch Stored Winner 分开。",
        "Scoring streams candidates into a min-heap of size K, finalizes deterministic order, then loads stored data only for winners.",
        "Scoring 把 Candidate 流入大小 K 的 Min Heap，确定最终顺序后只加载 Winner 的 Stored Data。",
        "The heap bound controls working memory, and score-plus-doc ordering makes ties reproducible across runs.",
        "Heap Bound 控制工作内存，Score 加 Doc 排序让 Tie 在多次运行间可复现。",
    ),
    LessonFacts(
        "Immutable segment images",
        "不可变 Segment Image",
        "The in-memory segment needs a canonical value object before a disk codec can preserve it exactly.",
        "内存 Segment 在交给磁盘 Codec 前，需要一个可被精确保留的 Canonical Value Object。",
        "Round-trip and validation tests construct mismatched doc counts, postings, norms, and stored fields.",
        "Round-trip 与 Validation 测试构造不一致的 Doc Count、Posting、Norm 与 Stored Field。",
        "A SegmentImage is the complete immutable logical payload, independent of file layout and publication protocol.",
        "SegmentImage 是完整不可变逻辑 Payload，独立于文件布局与发布协议。",
        "Builders normalize maps and tuples, validate cross-table counts and doc IDs, and expose one deterministic image to codecs.",
        "Builder 归一化 Map 与 Tuple，校验跨表 Count 与 Doc ID，再向 Codec 暴露唯一确定 Image。",
        "Separating logical image from bytes lets format validation and filesystem atomicity evolve without changing search semantics.",
        "把逻辑 Image 与字节分离，让格式校验和文件系统原子性可以演进而不改变 Search 语义。",
    ),
    LessonFacts(
        "Bounded varint primitives",
        "有界 Varint 原语",
        "A compact integer encoding becomes unsafe if truncation, overflow, signedness, or non-canonical forms are implicit.",
        "若截断、Overflow、Signedness 或非 Canonical Form 隐含不明，紧凑整数编码就不安全。",
        "The suite feeds truncated, overlong, negative, and non-canonical encodings, including boolean values that masquerade as integers.",
        "测试输入截断、过长、负数与非 Canonical Encoding，并包含伪装成 Integer 的 Boolean。",
        "Unsigned varints encode small non-negative integers in continuation bytes under an explicit maximum bit width.",
        "Unsigned Varint 在显式最大 Bit Width 下，用 Continuation Byte 编码小型非负整数。",
        "Encoding rejects invalid Python values and emits a canonical byte sequence; decoding counts bytes and bits before returning a value.",
        "Encoding 拒绝非法 Python Value 并输出 Canonical Byte Sequence；Decoding 在返回前统计 Byte 与 Bit。",
        "The byte-count bound turns malicious continuation bytes into a typed failure instead of an unbounded loop or oversized integer.",
        "Byte Count Bound 把恶意 Continuation Byte 变成类型化失败，而非无限循环或超大整数。",
    ),
    LessonFacts(
        "Educational segment codec",
        "教学用 Segment Codec",
        "A logical image is not durable until every table has an explicit binary layout and cross-file consistency checks.",
        "逻辑 Image 只有在每张表具备显式二进制布局与跨文件一致性检查后才可持久。",
        "Codec tests corrupt lengths, term order, doc deltas, positions, and trailing bytes across the four segment files.",
        "Codec 测试破坏四个 Segment File 中的 Length、Term Order、Doc Delta、Position 与尾随字节。",
        "The codec splits terms, postings, stored fields, and norms into bounded canonical frames while preserving one shared document space.",
        "Codec 把 Term、Posting、Stored Field 与 Norm 拆成有界 Canonical Frame，同时保留共享 Document Space。",
        "Encode orders tables and delta-encodes monotonic IDs; decode validates headers, counts, bounds, ordering, and full input consumption.",
        "Encode 排序 Table 并 Delta Encode 单调 ID；Decode 校验 Header、Count、Bound、Order 与完整输入消费。",
        "Rejecting trailing or non-canonical bytes makes one logical image map to one accepted representation, simplifying integrity evidence.",
        "拒绝尾随或非 Canonical Byte，使一个逻辑 Image 只对应一种可接受表示，简化 Integrity Evidence。",
    ),
    LessonFacts(
        "Checksummed segment publication",
        "带校验和的 Segment 发布",
        "Several correctly encoded files can still be partially written or mixed across generations.",
        "多个正确编码文件仍可能被部分写入，或混合不同代次。",
        "Failure injection stops publication between temporary writes, checksums, fsync, and rename, then reopens the directory.",
        "Failure Injection 在临时写、Checksum、Fsync 与 Rename 之间停止发布，再重开目录。",
        "A segment store publishes an immutable directory only after every file and metadata digest is complete and durable.",
        "Segment Store 只有在每个文件与 Metadata Digest 完整持久后，才发布不可变目录。",
        "It writes a temporary sibling, fsyncs files and directory, records SHA-256 metadata, atomically renames, and verifies on read.",
        "它写临时 Sibling、Fsync 文件与目录、记录 SHA-256 Metadata、原子 Rename，并在读取时验证。",
        "The final rename is the visibility boundary; checksummed children prepared beforehand ensure readers never accept a mixed segment.",
        "最终 Rename 是可见性边界；预先准备好的带校验 Child 确保 Reader 不接受混合 Segment。",
    ),
    LessonFacts(
        "Manifest commit root",
        "Manifest 提交根",
        "A durable segment is not necessarily part of the committed index; restart needs one authoritative root.",
        "已持久 Segment 不一定属于已提交 Index；Restart 需要唯一权威 Root。",
        "Tests create orphan segments, corrupt candidate manifests, and interrupt root replacement to require old-root-or-new-root recovery.",
        "测试创建 Orphan Segment、损坏 Candidate Manifest，并中断 Root Replacement，要求恢复结果只能是旧 Root 或新 Root。",
        "The manifest names the committed segment generation and schema fingerprint. Its atomic replacement publishes the index root.",
        "Manifest 命名已提交 Segment Generation 与 Schema Fingerprint；其原子替换发布 Index Root。",
        "Commit writes and fsyncs a candidate manifest, replaces the root file, fsyncs the directory, and validates referenced children on reopen.",
        "Commit 写并 Fsync Candidate Manifest、替换 Root File、Fsync Directory，并在重开时验证引用的 Child。",
        "Readers follow only the published root, so unreferenced durable files remain orphans rather than becoming synthesized commits.",
        "Reader 只跟随已发布 Root，因此未引用的持久文件仍是 Orphan，不会变成拼接出的 Commit。",
    ),
    LessonFacts(
        "Index lifecycle ownership",
        "Index 生命周期所有权",
        "Storage components exist, but no object yet owns schema identity, writer exclusivity, open/close state, and directory resources.",
        "存储组件已存在，但尚无对象统一拥有 Schema Identity、Writer Exclusivity、Open/Close State 与 Directory Resource。",
        "The contract opens conflicting writers, crosses schema fingerprints, uses closed handles, and repeats close operations.",
        "契约打开冲突 Writer、跨 Schema Fingerprint、使用已关闭 Handle，并重复 Close。",
        "An IndexDirectory owns durable stores and writer leases; an IndexWriter owns buffered mutation and publication lifecycle.",
        "IndexDirectory 拥有 Durable Store 与 Writer Lease；IndexWriter 拥有 Buffered Mutation 与 Publication Lifecycle。",
        "Open validates or establishes schema identity, grants one writer lease, and every public operation checks lifecycle state before mutation.",
        "Open 校验或建立 Schema Identity、授予唯一 Writer Lease，并让每个 Public Operation 在 Mutation 前检查 Lifecycle State。",
        "Central ownership turns use-after-close and competing writers into immediate typed errors rather than delayed disk corruption.",
        "集中所有权把 Use-after-close 与竞争 Writer 变成立即类型错误，而非延迟磁盘损坏。",
    ),
    LessonFacts(
        "Writer flush",
        "Writer Flush",
        "Buffered documents are searchable nowhere and durable nowhere until one operation freezes them into a segment.",
        "Buffered Document 在被一次操作冻结成 Segment 前，既不可搜索也不持久。",
        "Tests cross document and byte thresholds, inject publication failure, and verify a failed flush keeps the buffer retryable.",
        "测试跨越 Document/Byte Threshold、注入 Publication Failure，并验证失败 Flush 保持 Buffer 可重试。",
        "Flush converts the current mutable RAM buffer into one immutable segment without publishing a commit or a new reader view.",
        "Flush 把当前 Mutable RAM Buffer 转成一个 Immutable Segment，但不发布 Commit 或新 Reader View。",
        "The writer swaps or snapshots its buffer, builds an image, publishes the segment, then records it as uncommitted only after success.",
        "Writer Swap 或 Snapshot 当前 Buffer、构建 Image、发布 Segment，并且只在成功后记录为 Uncommitted。",
        "Clearing the buffer after publication preserves retry safety: failure leaves the same documents available for another flush.",
        "只在发布后清空 Buffer 保持 Retry Safety：失败时同一批 Document 仍可再次 Flush。",
    ),
    LessonFacts(
        "Atomic commit and reopen",
        "原子 Commit 与重开",
        "Flushed segments survive on disk but remain invisible after restart until the manifest root publishes them.",
        "Flushed Segment 虽已在磁盘，却要等 Manifest Root 发布后才能在 Restart 后可见。",
        "Commit tests fail before and during root replacement, reopen repeatedly, and require either the complete previous generation or the complete next one.",
        "Commit 测试在 Root Replacement 前和过程中失败、反复重开，并要求只看到完整上一代或下一代。",
        "Commit is a publication protocol over already durable segment children; reopen reconstructs an index strictly from the current manifest.",
        "Commit 是已持久 Segment Child 之上的发布协议；Reopen 严格从当前 Manifest 重建 Index。",
        "The writer flushes, prepares all referenced children, writes the next manifest, atomically swaps the root, and advances committed generation only after success.",
        "Writer 先 Flush、准备全部引用 Child、写下一 Manifest、原子 Swap Root，并只在成功后推进 Committed Generation。",
        "Fsyncing children before the root and the directory after replacement establishes the crash-ordering proof.",
        "Root 前 Fsync Child、Replacement 后 Fsync Directory，建立 Crash Ordering 证明。",
    ),
    LessonFacts(
        "Point-in-time reader snapshots",
        "时间点 Reader Snapshot",
        "A reader that follows writer mutation in place cannot offer stable results across refresh, delete, or merge.",
        "若 Reader 原地跟随 Writer Mutation，就无法在 Refresh、Delete 或 Merge 间提供稳定结果。",
        "Tests open an old reader, publish newer state, and prove the old reader's segments, live docs, statistics, and hits do not change.",
        "测试打开旧 Reader、发布新状态，并证明旧 Reader 的 Segment、Live Docs、Statistic 与 Hit 不变。",
        "A reader snapshot freezes segment identities and visibility metadata at open time and owns references to those immutable resources.",
        "Reader Snapshot 在 Open 时冻结 Segment Identity 与 Visibility Metadata，并拥有这些不可变资源的引用。",
        "Opening captures the current publication view; search reads only captured objects; closing releases ownership without consulting later writer state.",
        "Open 捕获当前 Publication View；Search 只读取捕获对象；Close 释放 Ownership 且不查询后续 Writer State。",
        "Copying the reference set, not mutable contents, is enough because segments are immutable and visibility overlays are versioned.",
        "因为 Segment 不可变且 Visibility Overlay 有版本，只复制 Reference Set 而非内容就足够。",
    ),
    LessonFacts(
        "Near-real-time refresh",
        "Near-real-time Refresh",
        "Waiting for a durable commit before every search makes newly flushed data unnecessarily invisible in the running process.",
        "每次搜索都等待 Durable Commit，会让已 Flush 新数据在进程内不必要地不可见。",
        "The contract distinguishes buffered, flushed, refreshed, committed, and reopened views across one document timeline.",
        "契约沿一条 Document Timeline 区分 Buffered、Flushed、Refreshed、Committed 与 Reopened View。",
        "Refresh publishes a new in-process snapshot from current segments; commit publishes the restart root. Near-real-time describes visibility, not weaker indexing.",
        "Refresh 从当前 Segment 发布新的进程内 Snapshot；Commit 发布 Restart Root。Near-real-time 描述可见性而非较弱索引。",
        "Refresh flushes if needed, captures current segment/live-doc generations, and returns a reader without replacing the durable manifest.",
        "Refresh 必要时 Flush、捕获当前 Segment/Live-doc Generation，并返回 Reader，但不替换 Durable Manifest。",
        "Keeping refresh and commit separate explains why a document can be searchable now yet absent after a crash and reopen.",
        "把 Refresh 与 Commit 分开，解释了 Document 为何现在可搜索，却可能在 Crash/Reopen 后消失。",
    ),
    LessonFacts(
        "Immutable live-doc masks",
        "不可变 Live-doc Mask",
        "Immutable segment files cannot erase deleted documents in place without breaking old readers and checksums.",
        "不可变 Segment File 无法原地擦除删除 Document，否则会破坏旧 Reader 与 Checksum。",
        "Tests flip bits across boundaries, corrupt generations, and retain old masks while new readers observe a newer deletion view.",
        "测试跨边界翻转 Bit、损坏 Generation，并让旧 Mask 保留而新 Reader 观察更新删除视图。",
        "A live-doc mask is a versioned immutable visibility overlay; stored/posting data stays unchanged while a bit decides whether a local doc is visible.",
        "Live-doc Mask 是有版本的不可变 Visibility Overlay；Stored/Posting Data 不变，由 Bit 决定 Local Doc 是否可见。",
        "Mutation derives a new mask from the previous generation, writes and checksums it atomically, and publishes its generation in writer state.",
        "Mutation 从前一代派生新 Mask、原子写入并校验，再在 Writer State 发布其 Generation。",
        "Publishing a new generation instead of editing bytes lets old snapshots retain their exact deletion view.",
        "发布新 Generation 而非修改字节，让旧 Snapshot 保留准确的删除视图。",
    ),
    LessonFacts(
        "Delete by exact term",
        "按精确 Term 删除",
        "A deletion request must find matching live documents and publish visibility changes without mutating segment postings.",
        "删除请求必须找到匹配的 Live Document 并发布可见性变化，而不能修改 Segment Posting。",
        "Tests delete across RAM and disk segments, repeat deletion, refresh old/new readers, and commit/reopen the result.",
        "测试跨 RAM 与 Disk Segment 删除、重复删除、Refresh 新旧 Reader，并 Commit/Reopen 结果。",
        "Delete-by-term is derive-then-swap: evaluate one exact indexed term against each current segment, then publish new live-doc generations.",
        "Delete-by-term 是 Derive-then-swap：在每个当前 Segment 上求值一个精确 Indexed Term，再发布新 Live-doc Generation。",
        "The writer flushes pending additions when necessary, resolves matching local doc IDs, derives masks, and updates only successful segment generations.",
        "Writer 必要时 Flush Pending Add、解析匹配 Local Doc ID、派生 Mask，并只更新成功的 Segment Generation。",
        "Exact-term deletion intentionally bypasses query parsing and analysis so the mutation key has one unambiguous indexed representation.",
        "Exact-term Delete 有意绕过 Query Parsing 与 Analysis，使 Mutation Key 只有一种明确 Indexed Representation。",
    ),
    LessonFacts(
        "Update and live-only statistics",
        "Update 与仅 Live 统计",
        "Implementing update as add-then-delete can delete the replacement, and deleted documents must stop influencing ranking.",
        "把 Update 实现为先 Add 后 Delete 会删掉替代 Document，且已删除 Document 不应继续影响 Ranking。",
        "The counterexample updates multiple matches, injects add failure, and compares BM25 before and after deletions across snapshots.",
        "反例 Update 多个 Match、注入 Add Failure，并比较多个 Snapshot 中删除前后的 BM25。",
        "Update is delete-all matching old identity plus one validated add under one writer operation; corpus statistics count only live documents.",
        "Update 是在一次 Writer Operation 中删除全部旧身份匹配并加入一个已校验新 Document；Corpus Statistic 只统计 Live Document。",
        "The writer validates replacement first, derives deletion masks from the pre-update view, then buffers the new document; readers aggregate only live postings and norms.",
        "Writer 先校验 Replacement、从更新前 View 派生 Delete Mask，再 Buffer 新 Document；Reader 只聚合 Live Posting 与 Norm。",
        "Validating before deletion prevents a bad replacement from destroying old data; live filtering keeps ranking consistent with visible hits.",
        "删除前校验防止错误 Replacement 摧毁旧数据；Live Filtering 让 Ranking 与可见 Hit 一致。",
    ),
    LessonFacts(
        "Explicit segment merge",
        "显式 Segment Merge",
        "Many immutable segments increase lookup and file overhead, but merging must not resurrect deleted documents or renumber visible history incorrectly.",
        "大量 Immutable Segment 增加 Lookup 与文件开销，但 Merge 不能复活已删 Document 或错误重编号可见历史。",
        "Tests merge segments containing deletions, retain an old reader, inject output failure, and compare results before and after publication.",
        "测试合并含删除的 Segment、保留旧 Reader、注入 Output Failure，并比较发布前后结果。",
        "Merge captures immutable inputs, copies only live documents into a new dense segment, and swaps writer ownership after output publication.",
        "Merge 捕获不可变 Input，只把 Live Document 复制到新的 Dense Segment，并在 Output Publication 后交换 Writer Ownership。",
        "The writer pins input generations, builds a doc-ID remap and output image, publishes it, then replaces current segment references and retires inputs.",
        "Writer Pin 输入 Generation、构建 Doc-ID Remap 与 Output Image、发布后替换当前 Segment Reference 并 Retire Input。",
        "Publishing output before swapping state makes failure leave the old segment set authoritative and old readers valid.",
        "先发布 Output 再 Swap State，使失败时旧 Segment Set 仍权威且旧 Reader 有效。",
    ),
    LessonFacts(
        "Segment ownership and close",
        "Segment 所有权与 Close",
        "Obsolete files cannot be deleted merely because the writer stopped referencing them; readers may still own snapshots.",
        "不能因为 Writer 不再引用就删除 Obsolete File；Reader 可能仍拥有 Snapshot。",
        "The suite keeps readers across merge and close, opens owner zero, repeats cleanup, and exercises calls after writer or reader close.",
        "测试让 Reader 跨 Merge 与 Close 存活、打开 Owner Zero、重复 Cleanup，并在 Writer/Reader Close 后调用操作。",
        "An ownership registry tracks explicit reader/writer references. Obsolete means not current; collectible means obsolete with owner count zero.",
        "Ownership Registry 跟踪显式 Reader/Writer Reference。Obsolete 表示非当前；Collectible 表示 Obsolete 且 Owner Count 为零。",
        "Opening and closing readers acquire/release segment generations; writer swaps mark inputs obsolete; cleanup deletes only registry-approved generations.",
        "Reader Open/Close 获取或释放 Segment Generation；Writer Swap 标记 Input Obsolete；Cleanup 只删除 Registry 批准的 Generation。",
        "The zero-owner transition, not writer preference, is the safe deletion boundary; close must release each ownership exactly once.",
        "Owner Count 归零而非 Writer 偏好才是安全删除边界；Close 必须恰好释放每份 Ownership 一次。",
    ),
    LessonFacts(
        "Closed query lexer",
        "封闭 Query Lexer",
        "User query text needs tokens that preserve source spans and distinguish operators, phrases, prefixes, fields, and errors.",
        "用户 Query Text 需要保留 Source Span，并区分 Operator、Phrase、Prefix、Field 与 Error 的 Token。",
        "Lexer tests include escapes, unmatched quotes, illegal stars, hyphenated text, and exact error offsets.",
        "Lexer 测试包含 Escape、未闭 Quote、非法 Star、Hyphenated Text 与精确 Error Offset。",
        "The lexer is evidence-preserving translation from characters to a finite token vocabulary; it does not decide precedence or index meaning.",
        "Lexer 是从 Character 到有限 Token Vocabulary 的保留证据翻译；它不决定 Precedence 或 Index Meaning。",
        "A cursor consumes characters, records start/end spans, recognizes reserved syntax, and emits typed lexical failures at the first impossible byte.",
        "Cursor 消费 Character、记录 Start/End Span、识别 Reserved Syntax，并在第一个不可能 Byte 发出类型化 Lexical Failure。",
        "Keeping spans through tokenization lets later parser errors point to the user's original text rather than a normalized reconstruction.",
        "Tokenization 全程保留 Span，让后续 Parser Error 指向用户原文而非归一化重建文本。",
    ),
    LessonFacts(
        "Recursive-descent query parser",
        "递归下降 Query Parser",
        "Tokens remain ambiguous until precedence, grouping, field scope, unary operators, and implicit composition are explicit.",
        "Token 在 Precedence、Grouping、Field Scope、Unary Operator 与隐式组合明确前仍有歧义。",
        "Tests compare ASTs for mixed AND/OR/NOT, nested groups, fields, phrases, prefixes, and incomplete expressions.",
        "测试比较混合 AND/OR/NOT、嵌套 Group、Field、Phrase、Prefix 与不完整表达式的 AST。",
        "A recursive-descent layer per precedence level turns the closed token stream into the same closed query AST used by execution.",
        "每个 Precedence Level 一层递归下降，把封闭 Token Stream 转成执行使用的同一封闭 Query AST。",
        "Parsing advances tokens through OR, AND, unary, and primary functions, applies field scope deliberately, and requires full input consumption.",
        "Parsing 通过 OR、AND、Unary 与 Primary Function 推进 Token，有意应用 Field Scope，并要求完整消费输入。",
        "Full consumption rejects valid prefixes followed by garbage; separate precedence functions make grouping rules visible in code.",
        "完整消费拒绝后接垃圾的有效前缀；分离的 Precedence Function 让 Grouping Rule 在代码中可见。",
    ),
    LessonFacts(
        "Bounded prefix rewrite",
        "有界 Prefix Rewrite",
        "A prefix query cannot execute directly against exact-term postings, and unbounded expansion can turn one query into exhaustive work.",
        "Prefix Query 无法直接执行 Exact-term Posting，且无界展开会把一次 Query 变成穷举工作。",
        "Tests create more matching terms than the limit, vary default fields, and ensure deterministic expansion or a typed too-many-clauses failure.",
        "测试创建超过 Limit 的匹配 Term、改变 Default Field，并要求确定性 Expansion 或类型化 Too-many-clauses Failure。",
        "Rewrite translates a high-level prefix node into a bounded OR of exact TermQuery nodes using the current reader vocabulary.",
        "Rewrite 使用当前 Reader Vocabulary，把高层 Prefix Node 翻译成有界 Exact TermQuery OR。",
        "It resolves field context, enumerates sorted matching terms, stops after limit plus one, and recursively rewrites composite children.",
        "它解析 Field Context、枚举有序匹配 Term、在 Limit+1 停止，并递归 Rewrite Composite Child。",
        "Checking one term beyond the limit distinguishes an exactly-full valid rewrite from silent truncation that would lose matches.",
        "检查 Limit 之外一个 Term，区分恰好填满的合法 Rewrite 与会丢 Match 的静默截断。",
    ),
    LessonFacts(
        "Offset-based highlighting",
        "基于 Offset 的 Highlight",
        "Highlighting normalized query terms by searching raw strings fails under case folding, punctuation, repeated terms, and phrase boundaries.",
        "用字符串搜索在原文中 Highlight 归一化 Query Term，会在大小写、标点、重复 Term 与 Phrase Boundary 下失败。",
        "Tests use mixed case, repeated tokens, overlapping clauses, stored/non-stored fields, and fragment limits.",
        "测试使用混合大小写、重复 Token、重叠 Clause、Stored/Non-stored Field 与 Fragment Limit。",
        "Highlighting reuses analyzer offsets as the mapping from indexed evidence back to stored source text.",
        "Highlight 复用 Analyzer Offset，把索引证据映射回 Stored Source Text。",
        "The highlighter analyzes stored text with the field analyzer, selects token spans matched by rewritten query terms, merges overlaps, and builds bounded fragments.",
        "Highlighter 用 Field Analyzer 分析 Stored Text、选择 Rewritten Query Term 匹配的 Token Span、合并重叠并构建有界 Fragment。",
        "Offsets, not normalized token strings, preserve the exact original casing and punctuation inserted between highlight tags.",
        "Offset 而非归一化 Token String，保留 Highlight Tag 之间准确的原始大小写与标点。",
    ),
    LessonFacts(
        "Deterministic relevance evaluation",
        "确定性相关性评估",
        "A few hand-inspected hits cannot show whether ranking changes improve or regress a fixed retrieval task.",
        "少量人工查看 Hit 无法说明 Ranking 变化是在改进还是回归固定 Retrieval Task。",
        "Metric tests cover ties, missing judgments, empty relevant sets, cutoffs, and a frozen corpus with expected per-query results.",
        "Metric 测试覆盖 Tie、缺失 Judgment、空 Relevant Set、Cutoff 与带预期 Query Result 的冻结 Corpus。",
        "Precision, recall, average precision, reciprocal rank, and nDCG are deterministic functions of ranked IDs and qrels; fixtures freeze the evaluation world.",
        "Precision、Recall、AP、RR 与 nDCG 是 Ranked ID 与 Qrel 的确定函数；Fixture 冻结评估世界。",
        "The harness builds the reference index, runs declared queries, computes metrics at fixed cutoffs, and compares stable aggregates.",
        "Harness 构建 Reference Index、运行声明 Query、在固定 Cutoff 计算 Metric，并比较稳定 Aggregate。",
        "Explicit tie ordering and fixed fixtures make a score change observable as evidence rather than an anecdotal ranking impression.",
        "显式 Tie Ordering 与固定 Fixture，让 Score 变化成为可观察证据而非主观 Ranking 印象。",
    ),
    LessonFacts(
        "CLI and domain closure",
        "CLI 与领域闭环",
        "The core mechanisms need one thin user path and combined failure evidence without duplicating indexing or search semantics.",
        "核心机制需要一条轻量用户路径与组合失败证据，同时不能复制 Index/Search 语义。",
        "End-to-end and failure matrices combine commit, reopen, delete, merge, bad input, closed handles, and CLI process behavior.",
        "End-to-end 与 Failure Matrix 组合 Commit、Reopen、Delete、Merge、Bad Input、Closed Handle 与 CLI Process 行为。",
        "The CLI is an adapter over the public API; domain closure means lifecycle, persistence, ranking, and failure contracts survive composition.",
        "CLI 是 Public API 上的 Adapter；领域闭环意味着 Lifecycle、Persistence、Ranking 与 Failure Contract 经组合后仍成立。",
        "Commands parse bounded JSON arguments, open the same directory/writer/reader objects, call existing operations, serialize results, and preserve typed error exits.",
        "Command 解析有界 JSON Argument、打开同一 Directory/Writer/Reader Object、调用已有 Operation、序列化结果并保留类型化错误退出。",
        "An adapter may translate input and output but must not own alternate commit, query, scoring, or lifecycle rules.",
        "Adapter 可以翻译 Input/Output，但不得拥有另一套 Commit、Query、Scoring 或 Lifecycle Rule。",
    ),
    LessonFacts(
        "Query and token regressions",
        "Query 与 Token 回归",
        "Single-token quoted queries, hyphenated terms, invalid token attributes, zero-length statistics, and boolean varints expose gaps between documented and executable contracts.",
        "单 Token Quote、Hyphenated Term、非法 Token Attribute、零长度统计与 Boolean Varint 暴露文档契约与可执行契约间缺口。",
        "Regression tests preserve exact strings that the earlier lexer/parser accepted incorrectly and construct invalid Token and primitive values directly.",
        "回归测试保留早期 Lexer/Parser 错误处理的精确字符串，并直接构造非法 Token 与 Primitive Value。",
        "A regression Stage turns discovered counterexamples into permanent boundaries across parsing, analysis, scoring, and codec primitives.",
        "Regression Stage 把已发现反例变成 Parsing、Analysis、Scoring 与 Codec Primitive 的永久边界。",
        "The parser recognizes one-term phrases without collapsing quote evidence; the lexer keeps hyphens inside terms; constructors and primitives validate values at creation.",
        "Parser 识别单 Term Phrase 而不丢 Quote Evidence；Lexer 保留 Term 内 Hyphen；Constructor 与 Primitive 在创建时校验 Value。",
        "Validation must live at the earliest owning boundary, so every downstream caller receives an already-valid Token, score denominator, or integer.",
        "Validation 必须位于最早的所有权边界，使每个下游调用方收到的 Token、Score Denominator 或 Integer 已经有效。",
    ),
    LessonFacts(
        "Document-at-a-time execution",
        "Document-at-a-time 执行",
        "Materializing full result sets for every query node hides streaming behavior and scales with all matches before Top-K can discard most of them.",
        "为每个 Query Node 物化完整 Result Set 会隐藏流式行为，并在 Top-K 丢弃多数结果前就按全部 Match 扩张。",
        "Differential tests generate nested boolean queries and require DAAT hits and scores to equal the existing set-based oracle, including fallback cases.",
        "差分测试生成嵌套 Boolean Query，并要求 DAAT Hit 与 Score 等于既有 Set-based Oracle，包含 Fallback Case。",
        "A doc iterator exposes current doc ID and monotonic advance; conjunction aligns cursors, disjunction heap-merges them, exclusion filters a required stream, and streaming scorers retain BM25 evidence.",
        "Doc Iterator 暴露 Current Doc ID 与单调 Advance；Conjunction 对齐 Cursor，Disjunction 用 Heap Merge，Exclusion 过滤 Required Stream，Streaming Scorer 保留 BM25 Evidence。",
        "The planner builds iterator/scorer trees from rewritten queries, collectors consume candidates without stored fields, and a second phase fetches only winners.",
        "Planner 从 Rewritten Query 构建 Iterator/Scorer Tree，Collector 在不取 Stored Field 的情况下消费 Candidate，第二阶段只 Fetch Winner。",
        "Differential equality makes the old executor an oracle while the new iterator contract changes cost and control flow without silently changing semantics.",
        "差分相等让旧 Executor 成为 Oracle，使新 Iterator Contract 改变成本与控制流而不悄悄改变语义。",
    ),
)
